version: 1.0.{build}
image: Visual Studio 2019
clone_folder: c:\project
environment:
  RELOADEDII: c:\project\build
build_script:
- cmd: >-
    git submodule update --init --recursive

    dotnet restore

    msbuild PreappPartnersLib.sln /p:Configuration=Debug /p:OutputPath=c:\project\build\debug

    msbuild PreappPartnersLib.sln /p:Configuration=Release /p:OutputPath=c:\project\build\release
artifacts:
- path: build/release
  name: release
- path: build/debug
  name: debug